const trainingData = [
    // Démarrer le chatbot
    { input: "bonjour", output: "start" },
    { input: "salut", output: "start" },
    { input: "hello", output: "start" },
    { input: "commencer", output: "start" },
    { input: "démarrer", output: "start" },
    { input: "aide", output: "start" },
    { input: "help", output: "start" },
    { input: "démarrer le chat", output: "start" },
    { input: "comment ça marche", output: "start" },
    { input: "je veux commencer", output: "start" },
    
    // Connexion par email
    { input: "se connecter", output: "login" },
    { input: "connexion", output: "login" },
    { input: "je suis déjà membre", output: "login" },
    { input: "j'ai un compte", output: "login" },
    { input: "oui je suis membre", output: "login" },
    { input: "login", output: "login" },
    { input: "accéder à mon compte", output: "login" },
    { input: "je veux me connecter", output: "login" },
    { input: "authentification", output: "login" },
    { input: "je suis client", output: "login" },
    
    // Créer un profil utilisateur
    { input: "nouveau client", output: "register" },
    { input: "je ne suis pas membre", output: "register" },
    { input: "je n'ai pas de compte", output: "register" },
    { input: "non je ne suis pas membre", output: "register" },
    { input: "s'inscrire", output: "register" },
    { input: "créer un profil", output: "register" },
    { input: "nouvel utilisateur", output: "register" },
    { input: "je suis nouveau", output: "register" },
    { input: "première visite", output: "register" },
    { input: "je débute", output: "register" },
    
    // Liste des offres disponibles
    { input: "liste des offres", output: "listOffers" },
    { input: "offres disponibles", output: "listOffers" },
    { input: "quelles sont les offres", output: "listOffers" },
    { input: "comparer les offres", output: "listOffers" },
    { input: "plans tarifaires", output: "listOffers" },
    { input: "options bancaires", output: "listOffers" },
    { input: "formules bancaires", output: "listOffers" },
    { input: "types de comptes", output: "listOffers" },
    { input: "voir les offres", output: "listOffers" },
    { input: "tarifs", output: "listOffers" },
    
    // Solde du compte
    { input: "solde de mon compte", output: "balance" },
    { input: "combien j'ai sur mon compte ?", output: "balance" },
    { input: "montant de mon solde", output: "balance" },
    { input: "je veux voir mon solde", output: "balance" },
    { input: "quel est mon solde actuel ?", output: "balance" },
    { input: "combien d'argent ai-je ?", output: "balance" },
    { input: "mon solde bancaire", output: "balance" },
    { input: "état de mon compte", output: "balance" },
    { input: "solde disponible", output: "balance" },
    { input: "mon compte fait combien ?", output: "balance" },
 
    // Historique des transactions
    { input: "historique de mes transactions", output: "history" },
    { input: "affiche mes paiements", output: "history" },
    { input: "liste des transactions récentes", output: "history" },
    { input: "mes derniers mouvements bancaires", output: "history" },
    { input: "je veux voir mes dernières transactions", output: "history" },
    { input: "historique des achats", output: "history" },
    { input: "mes mouvements de compte", output: "history" },
    { input: "relève de mes opérations", output: "history" },
    { input: "détail de mes transactions", output: "history" },
    { input: "mes opérations bancaires", output: "history" },
 
    // Retrait d'argent
    { input: "je veux retirer de l'argent", output: "withdraw" },
    { input: "faire un retrait", output: "withdraw" },
    { input: "retirer du cash", output: "withdraw" },
    { input: "enlever de l'argent de mon compte", output: "withdraw" },
    { input: "comment retirer de l'argent ?", output: "withdraw" },
    { input: "je souhaite faire un retrait", output: "withdraw" },
    { input: "sortie d'espèces", output: "withdraw" },
    { input: "prélèvement d'argent", output: "withdraw" },
    { input: "retrait au guichet", output: "withdraw" },
    { input: "combien puis-je retirer ?", output: "withdraw" },
 
    // Virement bancaire
    { input: "faire un virement", output: "transfer" },
    { input: "envoyer de l'argent", output: "transfer" },
    { input: "transférer de l'argent sur un autre compte", output: "transfer" },
    { input: "effectuer un transfert", output: "transfer" },
    { input: "virement vers un autre compte", output: "transfer" },
    { input: "comment faire un virement ?", output: "transfer" },
    { input: "transmettre des fonds", output: "transfer" },
    { input: "envoi d'argent", output: "transfer" },
    { input: "virement international", output: "transfer" },
    { input: "transférer de l'argent à quelqu'un", output: "transfer" },
 
    // Recharger une carte
    { input: "recharger ma carte", output: "rechargeCard" },
    { input: "ajouter de l'argent sur ma carte", output: "rechargeCard" },
    { input: "mettre du crédit sur ma carte bancaire", output: "rechargeCard" },
    { input: "charger ma carte", output: "rechargeCard" },
    { input: "réapprovisionner ma carte", output: "rechargeCard" },
    { input: "je veux alimenter ma carte", output: "rechargeCard" },
    { input: "crédit sur ma carte", output: "rechargeCard" },
    { input: "recharge de ma carte bancaire", output: "rechargeCard" },
    { input: "ajout de fonds sur ma carte", output: "rechargeCard" },
    { input: "comment recharger ma carte ?", output: "rechargeCard" },
 
    // Afficher mes cartes
    { input: "afficher mes cartes", output: "getCards" },
    { input: "voir mes cartes bancaires", output: "getCards" },
    { input: "liste de mes cartes", output: "getCards" },
    { input: "mes cartes disponibles", output: "getCards" },
    { input: "quelles cartes ai-je ?", output: "getCards" },
    { input: "mes cartes en cours", output: "getCards" },
    { input: "inventaire de mes cartes", output: "getCards" },
    { input: "carte bancaire active", output: "getCards" },
    { input: "consulter mes cartes", output: "getCards" },
    { input: "mes moyens de paiement", output: "getCards" },
 
    // Supprimer une carte
    { input: "supprimer une carte", output: "deleteCard" },
    { input: "bloquer une carte", output: "deleteCard" },
    { input: "désactiver une carte bancaire", output: "deleteCard" },
    { input: "annuler une carte", output: "deleteCard" },
    { input: "faire opposition à une carte", output: "deleteCard" },
    { input: "je veux désactiver ma carte", output: "deleteCard" },
    { input: "mettre mon opposition", output: "deleteCard" },
    { input: "annulation de carte", output: "deleteCard" },
    { input: "stopper ma carte", output: "deleteCard" },
    { input: "désactiver mon moyen de paiement", output: "deleteCard" },
 
    // Créer un compte bancaire
    { input: "créer un compte bancaire", output: "createAccount" },
    { input: "ouvrir un compte", output: "createAccount" },
    { input: "créer un compte", output: "createAccount" },
    { input: "faire une ouverture de compte", output: "createAccount" },
    { input: "je veux un nouveau compte", output: "createAccount" },
    { input: "ouverture de compte bancaire", output: "createAccount" },
    { input: "comment créer un compte ?", output: "createAccount" },
    { input: "nouvelle ouverture bancaire", output: "createAccount" },
    { input: "je souhaite ouvrir un compte", output: "createAccount" },
    { input: "nouveau compte bancaire", output: "createAccount" },
    { input: "procédure d'ouverture de compte", output: "createAccount" },
 
    // Détails d'une offre
    { input: "détails d'une offre", output: "offerDetails" },
    { input: "informations sur une offre", output: "offerDetails" },
    { input: "montre-moi l'offre", output: "offerDetails" },
    { input: "voir les avantages de l'offre", output: "offerDetails" },
    { input: "je veux connaître les conditions", output: "offerDetails" },
    { input: "quels sont les détails de l'offre ?", output: "offerDetails" },
    { input: "description de l'offre", output: "offerDetails" },
    { input: "caractéristiques de l'offre", output: "offerDetails" },
    { input: "informations détaillées", output: "offerDetails" },
    { input: "avantages et conditions", output: "offerDetails" },
 
    // Supprimer un compte
    { input: "supprimer mon compte", output: "deleteAccount" },
    { input: "fermer mon compte bancaire", output: "deleteAccount" },
    { input: "détruire mon compte", output: "deleteAccount" },
    { input: "annuler mon compte", output: "deleteAccount" },
    { input: "je veux clôturer mon compte", output: "deleteAccount" },
    { input: "mettre fin à mon compte", output: "deleteAccount" },
    { input: "clôture de compte", output: "deleteAccount" },
    { input: "comment fermer mon compte ?", output: "deleteAccount" },
    { input: "suppression de mon compte bancaire", output: "deleteAccount" },
    { input: "je souhaite me désinscrire", output: "deleteAccount" }
];
 
module.exports = trainingData;